import smtplib
import os
from email.message import EmailMessage
from dotenv import load_dotenv
from linkedin_oneclick import create_linkedin_button

load_dotenv()

EMAIL = os.getenv("EMAIL_ADDRESS")
PASSWORD = os.getenv("EMAIL_APP_PASSWORD")


def send_email(post):

    linkedin_button = create_linkedin_button(post)

    html_content = f"""
    <html>
        <body style="
            font-family: Arial, sans-serif;
            background-color:#f4f6f8;
            padding:40px;
        ">

            <div style="
                max-width:700px;
                margin:auto;
                background:white;
                padding:40px;
                border-radius:12px;
                box-shadow:0 5px 20px rgba(0,0,0,0.08);
            ">

                <h2 style="margin-top:0;">
                    🚀 Your Founder Post Is Ready
                </h2>

                <p style="color:#555;">
                    Generated by your AI Founder Engine.
                </p>

                <hr style="margin:25px 0;">

                <div style="
                    font-size:18px;
                    line-height:1.7;
                    color:#111;
                    white-space:pre-wrap;
                ">
                {post}
                </div>

                {linkedin_button}

            </div>

        </body>
    </html>
    """

    msg = EmailMessage()

    msg["Subject"] = "🚀 Your Founder Post Is Ready"
    msg["From"] = EMAIL
    msg["To"] = EMAIL

    msg.set_content(post)
    msg.add_alternative(html_content, subtype="html")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(EMAIL, PASSWORD)
        smtp.send_message(msg)

    print("Premium founder email sent successfully!")
